export const SET_MAIN_ROUTE = 'SET_MAIN_ROUTE';

export const FETCH_HOME_DATA_REQUEST_1 = 'FETCH_HOME_DATA_REQUEST_1';
export const FETCH_HOME_DATA_SUCCESS_1 = 'FETCH_HOME_DATA_SUCCESS_1';
export const FETCH_HOME_DATA_FAILURE_1 = 'FETCH_HOME_DATA_FAILURE_1';

export const FETCH_HOME_DATA_REQUEST_2 = 'FETCH_HOME_DATA_REQUEST_2';
export const FETCH_HOME_DATA_SUCCESS_2 = 'FETCH_HOME_DATA_SUCCESS_2';
export const FETCH_HOME_DATA_FAILURE_2 = 'FETCH_HOME_DATA_FAILURE_2';

export const FETCH_HOME_DATA_REQUEST_3 = 'FETCH_HOME_DATA_REQUEST_3';
export const FETCH_HOME_DATA_SUCCESS_3 = 'FETCH_HOME_DATA_SUCCESS_3';
export const FETCH_HOME_DATA_FAILURE_3 = 'FETCH_HOME_DATA_FAILURE_3';

export const FETCH_CART_DATA_REQUEST = 'FETCH_CART_DATA_REQUEST';
export const FETCH_CART_DATA_SUCCESS = 'FETCH_CART_DATA_SUCCESS';
export const FETCH_CART_DATA_FAILURE = 'FETCH_CART_DATA_FAILURE';
